---
sudo: required

language: shell

services:
  - docker

before_install:
  - gem install inspec -v 1.49.2
  - sudo curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

script:
 - find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:v0.4.7 "$line"; done
 - test/test-docker-images.sh --docker-context-path=./docker

matrix:
  fast_finish: true
