---
sudo: required

language: shell

services:
  - docker

matrix:
  fast_finish: true

jobs:
  include:
    - stage: lint all shell scripts
      script: find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck:v0.4.7 "$line"; done
    - stage: lint dockerfiles
      script: test/test-docker-images.sh --docker-context-path=docker --only=lint-dockerfile
    - stage: lint docker shell scripts
      script: test/test-docker-images.sh --docker-context-path=docker --only=lint-dockerfile
    - stage:   build images
      script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="zookeeper"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="kafka"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="flume"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="semantics"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="logstash"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="logstash24"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="datasource24"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="d-streamon-master"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="d-streamon-slave"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="prelude-manager-db"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="prelude-manager"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="event-correlator"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="prewikka"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="kafka-idmef-converter"
    - script:  docker-compose --file docker/docker-compose.yml build $IMAGE_NAME
      env:
        - IMAGE_NAME="kafka-prelude-connector"
    - stage: run integration tests
      before_install:
        - gem install inspec -v 2.1.30
        - sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      script: test/test-docker-images.sh --docker-context-path=./docker --only=integration

stages:
  - lint all shell scripts
  - lint dockerfiles
  - lint docker shell scripts
  - build images
  - run integration tests
