---
sudo: required

language: shell

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck
  - docker pull lukasmartinelli/hadolint
  - docker pull redcoolbeans/dockerlint

script:
 - find . -name '*.sh' | xargs docker run -v $(pwd):/mnt --rm koalaman/shellcheck-alpine
 - find . -name 'Dockerfile' | xargs docker run -v $(pwd):/mnt --rm -w="/mnt" lukasmartinelli/hadolint hadolint
 - find . -name 'Dockerfile' | xargs docker run -v $(pwd):/mnt --rm -w="/mnt" redcoolbeans/dockerlint

matrix:
  fast_finish: true
