cache:
  - C:\downloads -> appveyor.yml
environment:
  VAGRANT_URL: https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.msi
  VIRTUALBOX_URL: http://download.virtualbox.org/virtualbox/5.1.30/VirtualBox-5.1.30-118389-Win.exe
os: Windows Server 2012
platform:
  - x64
test: off
version: '{branch}-{build}'

init:
- ps: |
    mkdir C:\downloads | Out-Null
    cd C:\downloads
    Start-FileDownload "$env:VAGRANT_URL" -FileName vagrant.msi
    Start-Process -FilePath "msiexec.exe" -ArgumentList "/a vagrant.msi /qb TARGETDIR=C:\Vagrant" -Wait
    Start-FileDownload "$env:VIRTUALBOX_URL" -FileName virtualbox.exe
    Start-Process -FilePath "virtualbox.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox" -Wait
    cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
    While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
        echo "waiting for network..."
        Start-Sleep 1
    }
install:
- set PATH=C:\Vagrant\HashiCorp\Vagrant\bin;C:\VBox;%PATH%
- vagrant -v
- VBoxManage -v
build_script:
- ps: Test-NetConnection google.com -Port 80
- vagrant validate
